server:
  port: 9999
spring:
  application:
    name: kafkalistener
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: 192.168.99.100
          defaultZkPort: 2181
          brokers: 192.168.99.100
          defaultBrokerPort: 9092