server:
  port: 9999
spring:
  application:
    name: kafkalistener
  cloud:
    stream:
      kafka:
        binder:
          defaultZkPort: 2181
          brokers: 192.168.99.100
          defaultBrokerPort: 9092
  kafka:
    consumer:
      group-id: group_x
      bootstrap-servers: 192.168.99.100:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.gomezrondon.kafka.testkafkastreamconsumer.PageViewEventDeserial